### ISSUE TITLE
Looks like a great package. A suggestion for naming convention.

### ISSUE THREAD

**Issue by sbromberger** [zekeriyasari/Jusdl.jl#17]
Hi,

Just wanted to point out that mutating functions in Julia usually end with a `!`. Therefore, `addnode()` should probably be renamed `addnode!()` since it's modifying its first argument (the model).

Cheers!

**Comment by zekeriyasari** [comment]
Thank you very much for your suggestion @sbromberger  and thank you for all your efforts in LightGraphs.jl

I can rename the functions as you suggested. But I wonder your thoughts about my considerations that led me to name those functions like so.

During the design stage, I thought the same naming convention. That is, `funcname!(arg)` should be adopted instead of `funcname(arg)` if `arg` is mutated by the function. In the [style guide section of Julia docs](https://docs.julialang.org/en/v1/manual/style-guide/#bang-convention-1), an example is given, and in that example, the function `double` mutates directly its argument `a`. So, there is nothing wrong with that example.

But, the thing with [addnode](https://github.com/zekeriyasari/Jusdl.jl/blob/7226af512f30e292656af0de7e4f39a2e994d561/src/models/model.jl#L80) and [addbranch](https://github.com/zekeriyasari/Jusdl.jl/blob/7226af512f30e292656af0de7e4f39a2e994d561/src/models/model.jl#L134) functions is that its not the first argument `model` that is being mutated *directly*. `addnode` function mutates the `nodes`  and the  `graph` fields by pushing new nodes and vertices, and `addbranch` function mutates the `branches` and the `graph` fields of the `model` by pushing new branches and edges. That is, the elements of `nodes`, `branches` and `graph` are begin mutated. Considering this fact, I named the functions as  `addnode` and `addbranch`  instead of `addnode!` and `addbranch!`.

Do you think I am wrong?

**Comment by sbromberger** [comment]
OK, I understand your approach.

The thing is, that by changing `model.nodes`, you're changing `model`. That is, nodes is (let's say) a vector. When you `push!` to that vector, you have no guarantees that the pointer to `nodes` isn't going to change out from under you (if you have to do a reallocation because the capacity is exceeded, for example). That means, that `model` is subject to change, since it holds a pointer to `nodes`. So yes, you're actually modifying `model` behind the scenes whenever `nodes` gets reallocated, since the pointer to `nodes` which is kept by `model` will change. Consider:

```
struct Foo                                                                                                                                     
    v::Vector{Int}                                                                                                                                 
end  
```
```
julia> f = Foo([])                                                                                                                                    
Foo(Int64[])             

julia> pointer(f.v)
Ptr{Int64} @0x00007fac0932eda0       
julia> push!(f.v, 1)
1-element Array{Int64,1}:            
 1     
       
julia> pointer(f.v)
Ptr{Int64} @0x00007fac0c9ba680       
```

and
```

julia> f = Foo([])
Foo(Int64[])

julia> g = Foo([])  # this vector has a different address than `f.v`.
Foo(Int64[])

julia> pointer(f.v)
Ptr{Int64} @0x00007fac0daae6c0
julia> pointer(g.v)
Ptr{Int64} @0x00007fac0daaec10
julia> f == g  # even though the contents of `f.v` and `g.v` are identical
false

julia> g = Foo(f.v)  # let's create a `g` whose vector points to `f.v` instead.
Foo(Int64[])
julia> f == g
true
```

In general, this is way too much detail. I think the general approach is that if you change any of a structs fields in a function, then you should use the `!` syntax. This way the users get a heads up that a comparison of identical models post-call is not guaranteed to remain identical.

**Comment by zekeriyasari** [comment]
I definitely see your point. The correct approach is using `!` syntax. 
I appreciate very much your explanations.

**Comment by sbromberger** [comment]
My pleasure. I'm glad to see other packages using LightGraphs :)

**Comment by zekeriyasari** [comment]
> My pleasure. I'm glad to see other packages using LightGraphs :)
LightGraphs is really an excellent package and through the course of the development Jusdl, I plan to use more and more of the tools provided by LightGraphs. I thank you and all the contributors for all your efforts.

**Comment by sbromberger** [comment]
Thanks for the kind words. Just a heads-up: LightGraphs 2.0 is going to be a major change to the API. You can try it out with the master branch now - we have deprecations for everything that's changing.

**Comment by zekeriyasari** [comment]
Yeah, I think you mean the changes that you mentioned in [your post in discourse](https://discourse.julialang.org/t/lightgraphs-users-and-other-interested-parties-please-opine-below/37660). I try to follow the changes from github repo, docs, discourse posts, etc.. Thanks for the warning.

**Comment by sbromberger** [comment]
Yeah, that post. The plan is to release 2.0 towards the end of the summer. Working on some final decisions, then we have GSOC, and some documentation rewriting.

**Comment by zekeriyasari** [comment]
I wish you all the best with your plans.
